repos:
  - repo: https://github.com/LiquidFun/aoc_tiles
    rev: 0.7.2
    hooks:
      - id: aoc-tiles
        args:
          - --auto-add-tiles-to-git=amend
          - --overwrite-year=2025
          - --count-as-solved-when=on_leaderboard
          - --what-to-show-on-right-side=checkmark
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
        args: ["--workspace"]
      - id: fmt
        args: ["--", "--check"]
